README.md
littlepay/main.py
tests/test_littlepay.py
tests/test_main.py

Small fixes to config handling:
* In tests that call out to the CLI via `subprocess.call()`, ensure a real config file if present is not used
* Simplify changing config files via CLI:
_Before:_
```console
$ littlepay config -c /path/to/config.yaml
```
_This PR:_
```console
$ littlepay config /path/to/config.yaml
```
_or_
```console
$ littlepay -c /path/to/config.yaml
```

Fix: configuration

---

README.md
littlepay/api/__init__.py
littlepay/api/client.py
littlepay/api/products.py
littlepay/commands/groups.py
littlepay/commands/products.py
littlepay/main.py
tests/api/test_client.py
tests/api/test_groups.py
tests/api/test_products.py
tests/commands/test_groups.py
tests/commands/test_products.py
tests/conftest.py
tests/test_main.py

* New command `littlepay products` lists the products in the active environment
* `littlepay products --filter <term>` filters the list by product ID, code, or description
* `littlepay products [--filter <term>] link <group_id>` links one or more products to a group
* `littlepay products [--filter <term>] unlink <group_id>` unlinks one or more products from a group
* `littlepay groups [--filter <term>] products` lists products linked to one or more groups
* `littlepay groups [--filter <term>] link <product_id>` links a product to one or more groups
* `littlepay groups [--filter <term>] unlink <product_id>` unlinks a product from one or more groups
With this PR, `littlepay` can entirely replace our helper scripts in [`benefits-secrets`](https://github.com/cal-itp/benefits-secrets/tree/main/ …

Feat: products

---

littlepay/api/client.py
littlepay/api/funding_sources.py
tests/api/test_funding_sources.py

Part of #10 
This PR adds a method to `Client` to take in a card token provided from hosted verification and get the corresponding funding source.

Feat(enrollment): funding source from card token

---

littlepay/api/client.py
littlepay/api/funding_sources.py
littlepay/api/groups.py
tests/api/test_funding_sources.py
tests/api/test_groups.py

Part of #10 
This PR adds a method to `Client` to link a funding source to a group using their IDs.

Feat(enrollment): link funding source to group

---

.github/workflows/scrape.yml
README.md
data/README.md
littlepay/api/groups.py
littlepay/api/products.py
littlepay/commands/groups.py
littlepay/commands/products.py
littlepay/main.py
tests/api/test_groups.py
tests/api/test_products.py
tests/commands/test_groups.py
tests/commands/test_products.py
tests/test_main.py

Closes #18 
Adds a new flag `--csv` to the `groups` and `products` commands, which formats the output from those commands (i.e. the list of groups/products) into simple CSV rather than the default Python representation.

CI: git scrape groups and products

---

littlepay/commands/configure.py
tests/commands/test_configure.py
tests/test_littlepay.py

`littlepay` and `littlepay config` shouldn't return an error when no participant is selected; this doesn't necessarily indicate a problem, just that the configuration has not been `switch`ed to a given participant.
This PR updates the message and returns `RESULT_SUCCESS`.
Especially useful in automated processes that may switch multiple times a la #19, e.g. to avoid [this failure in the workflow run](https://github.com/cal-itp/littlepay/actions/runs/8057179199/job/22007749080#step:4:35)

Fix: don't return error with no participant

---

littlepay/config.py
tests/test_config.py

Closes #21 
This PR makes it so a more helpful error will be raised if the user runs some command that tries to use `config.active_participant` when there is no active participant.

Refactor(cli): provide a more helpful error when no active participant

---

littlepay/commands/configure.py
littlepay/config.py
tests/test_config.py

Closes #24 
This PR allows the `configure` command to run and set up the config path without trying to authenticate into any environment. The user can then use `littlepay switch` to set the active env and participant.
This was prompted by the recent failure in https://github.com/cal-itp/benefits/actions/runs/8155949034. The workflow correctly detected that the QA environment was down, but the failures for prod were not from any outage on prod, but rather because the `configure` command was trying to connect to QA first.

Fix: allow `configure` to run without an active env

---

.github/workflows/release.yml

Feat: publishing to PyPI

---

.github/workflows/release.yml

Follow-up to #31 
Trying to resolve an error we're seeing with publishing: https://github.com/cal-itp/littlepay/actions/runs/8269089795/job/22623537304#step:7:19
```
Warning:  It looks like you are trying to use an API token to authenticate in the package index and your token value does not start with "pypi-" as it typically should. This may cause an authentication error. Please verify that you have copied your token properly if such an error occurs.
```
and 
```
Uploading distributions to https://test.pypi.org/legacy/
INFO     dist/calitp_littlepay-2024.3.1rc2-py3-none-any.whl (25.3 KB)           
INFO     dist/calitp-littlepay-2024.3.1rc2.tar.gz (36.9 KB)                     
INFO     username set by command options                                        
INFO     password set by …
```

Fix: use v1 of PyPI publish action

---

littlepay/api/groups.py
tests/api/test_groups.py

When linking a funding source to a concession group.
* concession_expiry must be a Python `datetime` instance
* for _aware_ `datetime` instances, ensure the `datetime` is in UTC
* for _naive_ `datetime` instances, assume the `datetime` is in UTC (making it _aware_)
More about aware/naive datetimes: https://docs.python.org/3/library/datetime.html#determining-if-an-object-is-aware-or-naive
Closes #17

Feat: accept optional concession_expiry

---

littlepay/commands/groups.py
littlepay/commands/products.py
littlepay/main.py
tests/commands/test_groups.py
tests/commands/test_products.py
tests/test_littlepay.py
tests/test_main.py

Fixes #32 
* `littlepay` by default (with no other args) doesn't run the configuration flow, instead printing usage and exiting with an error (this is how e.g. `git` works)
* `littlepay -v` and `littlepay --version` no longer create a config file nor do they need one to exist, simply printing the version and exiting with a success

Fix: cli version flags don't need a config file

---

littlepay/api/groups.py
tests/api/test_groups.py

Feat: add endpoint for migrating concession groups

---

littlepay/commands/groups.py
littlepay/main.py
tests/commands/test_groups.py
tests/test_main.py

Closes #47 
~Built off #48~
This PR adds a subcommand to the `groups` command called `migrate`. It calls the `client.migrate_concession_group` method that was implemented in #48 for all groups that are returned by any filters given. (If no filters are given, all groups are returned, so all groups would be migrated.)
See my [comment below](https://github.com/cal-itp/littlepay/pull/49#issuecomment-2038084172) on an error I'm seeing when I tried to use `migrate` in the QA environment.

Feat: command for group migration

---

littlepay/commands/groups.py
tests/commands/test_groups.py

Fixes #50 
Read more about generator expressions (also called generator comprehensions) in its [PEP](https://peps.python.org/pep-0289/) or [docs](https://docs.python.org/3/reference/expressions.html#generator-expressions)

Fix: allow group commands to iterate on the groups multiple times

---

MANIFEST.in

Excludes all files/dirs that aren't part of the Python package source, e.g. our local devcontainer files.
See more: https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html#controlling-files-in-the-distribution
1. In the devcontainer, `pip install build`
2. Remove any old local build artifacts e.g. `dist/`, `calitp_littlepay.egg-info/`
3. Run `python -m build`
4. View contents of `calitp-littlepay.*.tar.gz`
5. Confirm none of the excluded files/dirs are present

Chore: manifest file to exclude from source build

---

.gitignore

This small PR adds `.DS_Store` (automatically created by macOS) to the .gitignore file.

chore(git): add .DS_Store to .gitignore

---

littlepay/api/funding_sources.py
littlepay/api/groups.py
tests/api/test_funding_sources.py
tests/api/test_groups.py
tests/commands/test_groups.py
tests/conftest.py

Closes #60 
Refactors parsing of the common date fields `created_date`, `updated_date`, and `expiry_date` into a reusable base `dataclass`.

Feat: endpoint to get funding source linked groups

---

littlepay/api/client.py
littlepay/api/products.py
tests/api/test_client.py
tests/api/test_products.py

Fix: per_page param

---

littlepay/api/groups.py
tests/api/test_groups.py

This was found while testing cal-itp/benefits#2165 and is needed by that PR.
`update_concession_group_funding_source_expiry` assumed it would get a list of a `GroupFundingSource`s, but the API [documentation](https://docs.littlepay.io/reference/backoffice/tag/Products/#tag/Products/operation/UpdateConcession) says that the response will be 
```
{ "status_code": 204 }
````
and the QA environment behavior matches the documentation.

Fix: update group funding source expiry

---

pyproject.toml

Similar to https://github.com/cal-itp/benefits/pull/2346
I ran into this while working on #67

Chore: disable Pyright type-checking rules

---

littlepay/api/__init__.py
littlepay/api/client.py
littlepay/api/funding_sources.py
littlepay/api/groups.py
littlepay/api/products.py
tests/api/test_client.py
tests/api/test_funding_sources.py
tests/api/test_groups.py
tests/api/test_products.py

Closes #66 
This PR makes it so GET requests will allow unexpected fields in the response JSON. The main code changes was for `Client._get` to expect that it can call `from_kwargs` to instantiate the response object, and to add `from_kwargs` as a class method on all response dataclasses.
Looking at our `Client` code and usages of `_get`, `_post`, and `_put`, we see that it is really only `_get` that tries to hydrate specific response dataclasses. Endpoints that use `_put` and `_post` all pass in `dict` as the response class to hydrate.
So it is a sufficient fix to only change `Client._get`.

Fix: allow unexpected fields in responses
